language: php

php:
  - 5.4

env:
  - MONGO_VERSION=1.3.7
  - MONGO_VERSION=1.4.5
  - MONGO_VERSION=stable

services: mongodb

before_script:
  - yes '' | pecl -q install -f mongo-${MONGO_VERSION} && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer install --dev